#!/bin/bash
#
# SPDX-License-Identifier: 0BSD
# Part of badkeys: https://badkeys.info/

[ -e ~/.badkeystools ] && . ~/.badkeystools

TODAY="$(date -I)"
MYDIR="$(dirname $0)"
if [ -z "$DNSSEC_MONITOR_OUTDIR" ]; then
	OUTDIR="$MYDIR/out-$TODAY"
else
	OUTDIR="$DNSSEC_MONITOR_OUTDIR/out-$TODAY"
fi

if [ -d "$OUTDIR" ]; then
	echo "$OUTDIR exists already"
	exit 1
fi
mkdir "$OUTDIR"

echo "begin='$(date -Iseconds)'" >>"$OUTDIR/meta.toml"

TDIR=$(mktemp -d)

ln -s "$MERGELIST_DIR/_merge.txt" "$TDIR/dom.txt"

mkdir "$OUTDIR/keys"
parallel -a "$TDIR/dom.txt" -n 15 -j 100 --timeout 300 \
	"$MYDIR/getdnskeys" -p -o "$OUTDIR/keys"

find "$OUTDIR/keys" -type f -exec badkeys --dnssec {} \+ \
	2>"$OUTDIR/badkeys-errors.log" \
	1>"$OUTDIR/badkeys.log"

echo "vulnerable=$(wc -l <$OUTDIR/badkeys.log)" >>"$OUTDIR/meta.toml"
echo "errors=$(wc -l <$OUTDIR/badkeys-errors.log)" >>"$OUTDIR/meta.toml"

echo "end='$(date -Iseconds)'" >>"$OUTDIR/meta.toml"

$MYDIR/gendnssecrep "$OUTDIR" >"$OUTDIR/$TODAY-dnssec-badkeys.html"

# Output badkeys results at the end
cat "$OUTDIR/badkeys.log"

rm -r "$TDIR"
