#!/bin/bash
#
# SPDX-License-Identifier: 0BSD
# Part of badkeys: https://badkeys.info/

[ -e ~/.badkeystools ] && . ~/.badkeystools

TODAY="$(date -I)"
MYDIR="$(dirname $0)"
if [ -z "$DNSSEC_MONITOR_OUTDIR" ]; then
	OUTDIR="$MYDIR/out-$TODAY"
else
	OUTDIR="$DNSSEC_MONITOR_OUTDIR/out-$TODAY"
fi

if [ -d "$OUTDIR" ]; then
	echo "$OUTDIR exists already"
	exit 1
fi
mkdir "$OUTDIR"

echo "begin='$(date -Iseconds)'" >>"$OUTDIR/meta.toml"

TDIR=$(mktemp -d)

if [ -z "$USE_DOMCOP" ]; then
	# by default use the Tranco Top 1 Million list
	echo "toplist='Tranco'" >>"$OUTDIR/meta.toml"
	TRANCOID=$(curl -s https://tranco-list.eu/top-1m-id)
	echo "trancoid='$TRANCOID'" >>"$OUTDIR/meta.toml"

	TURL="https://tranco-list.eu/download/daily/tranco_${TRANCOID}-1m.csv.zip"
	curl -s "$TURL" \
		>"$TDIR/tranco.zip"

	unzip -q -d "$TDIR" "$TDIR/tranco.zip"

	sed -e 's:\r$::g' -e 's:^[0-9]*,::g' "$TDIR/top-1m.csv" \
		>"$TDIR/dom.txt"
else
	echo "toplist='DomCop'" >>"$OUTDIR/meta.toml"
	curl -s https://www.domcop.com/files/top/top10milliondomains.csv.zip \
		>"$TDIR/top10milliondomains.csv.zip"
	unzip -q -d "$TDIR" "$TDIR/top10milliondomains.csv.zip"

	tail -n +2 "$TDIR/top10milliondomains.csv" |
		sed -e 's:^"[0-9]*","::g' -e 's:".*::g' \
			>"$TDIR/dom.txt"
fi

mkdir "$OUTDIR/keys"
parallel -a "$TDIR/dom.txt" -n 15 -j 100 --timeout 300 \
	"$MYDIR/getdnskeys" -p -o "$OUTDIR/keys"

find "$OUTDIR/keys" -type f -exec badkeys --dnssec {} \+ \
	2>"$OUTDIR/badkeys-errors.log" \
	1>"$OUTDIR/badkeys.log"

echo "vulnerable=$(wc -l <$OUTDIR/badkeys.log)" >>"$OUTDIR/meta.toml"
echo "errors=$(wc -l <$OUTDIR/badkeys-errors.log)" >>"$OUTDIR/meta.toml"

echo "end='$(date -Iseconds)'" >>"$OUTDIR/meta.toml"

$MYDIR/gendnssecrep "$OUTDIR" >"$OUTDIR/dnssec-report-$TODAY.html"

# Output badkeys results at the end
cat "$OUTDIR/badkeys.log"

rm -r "$TDIR"
