#!/bin/bash
#
# SPDX-License-Identifier: 0BSD
# Part of badkeys: https://badkeys.info/
set -euo pipefail

MYDIR="$(dirname $0)"

DKIMSELS="$1"
DOMAINLIST="$2"
OUTKEYS="$3/keys"

mkdir "$OUTKEYS"

parallel -a "$DKIMSELS" \
	-n 100 -j 100 -u \
	"$MYDIR/getdkimkey" -p -o "$OUTKEYS"

parallel -a "$DOMAINLIST" \
	-n 100 -j 100 -u \
	"$MYDIR/getdkimkey" -b -s -p -o "$OUTKEYS"
