#!/bin/bash
#
# SPDX-License-Identifier: 0BSD
# Part of badkeys: https://badkeys.info/

[ -e ~/.badkeystools ] && . ~/.badkeystools

TODAY="$(date -I)"
MYDIR="$(dirname $0)"

if [ -z "$DNSSEC_MONITOR_OUTDIR" ]; then
	OUTDIR="$MYDIR/out-$TODAY"
else
	OUTDIR="$DKIM_MONITOR_OUTDIR/out-$TODAY"
fi

if [ -d "$OUTDIR" ]; then
	echo "$OUTDIR exists already"
	exit 1
fi
mkdir "$OUTDIR"

echo "begin='$(date -Iseconds)'" >>"$OUTDIR/meta.toml"

TDIR=$(mktemp -d)

if [ -z "$TESTMODE" ]; then
	"$MYDIR/syncdkimselsources"
	"$MYDIR/getalldkimselectors" "$OUTDIR/dkimselectors"

	sort -u "$OUTDIR"/dkimselectors/* "$DKIM_EXTRASELECTORS"/* \
		>"$OUTDIR/dkimselectors/_all.txt"

	ln -s "$MERGELIST_DIR/_merge.txt" "$TDIR/dom.txt"
else
	# Skip syncing new selectors, only use 10k each
	mkdir "$OUTDIR/dkimselectors/"
	sort -u "$DKIM_EXTRASELECTORS"/* | head -n 10000 \
		>"$OUTDIR/dkimselectors/_all.txt"

	head -n 10000 "$MERGELIST_DIR/_merge.txt" >"$TDIR/dom.txt"
fi

"$MYDIR/collectdkimkeys" "$OUTDIR/dkimselectors/_all.txt" \
	"$TDIR/dom.txt" "$OUTDIR"

find "$OUTDIR/keys" -type f -exec badkeys -aj --dkim {} \+ \
	2>"$OUTDIR/badkeys-dkim-errors.log" \
	1>"$OUTDIR/badkeys-dkim-log.json"

echo "end='$(date -Iseconds)'" >>"$OUTDIR/meta.toml"

rm -r "$TDIR"
